apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: default
  namespace:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <hpa>
  minReplicas: <min-replicas>
  maxReplicas: <max-replicas>
  targetCPUUtilizationPercentage: <e.g. 50>